cassandra:
  image: itszero/zipkin-cassandra
collector:
  image: itszero/zipkin-collector
  expose:
    - 9410
  ports:
    - 9410:9410
  links:
    - cassandra:db
query:
  image: itszero/zipkin-query
  expose:
    - 9411
  links:
    - cassandra:db
web:
  image: itszero/zipkin-web
  links:
    - query
  ports:
    - 8080:8080
  environment: {
    ROOTURL: "http://172.17.42.1:8080"
    }
djangoexample:
  image: prezi/django-zipkin
  links:
    - collector:scribehost
  ports:
    - 8000:8000
  environment: {
    ZIPKIN_SCRIBE_PORT: 9410,
    ZIPKIN_SCRIBE_HOST: scribehost
    }